-- liquibase formatted sql

-- changeset mprokhorova:1
CREATE TABLE notification_task (
    id BIGINT generated by default as identity primary key,
    id_chat BIGINT not null,
    text_notification TEXT not null,
    date_notification TIMESTAMP not null
)